### PR TITLE
Fix createsuperuser command

### PR DESCRIPTION
**Pull request by bryan-brancotte**
Hi Jon

The `python manage.py createsuperuser` was broken, here is a fix

### CODE REVIEW

**Comment by joncison** [comment]
Brilliant - thanks !  

Should ``homepage==None`` and ``orcid==None`` also be given for ``create_user``, i.e.
``    def create_user(self, firstname, lastname, email, orcidid=None, homepage=None, password=None):``

rather than:
`` def create_user(self, firstname, lastname, email, orcidid, homepage, password=None):``

(homepage and orcidid are not mandatory)
?

**Comment by bryan-brancotte** [comment]
You are welcome !

create_user should probably also have orcidid=None, homepage=None, but I did not know from where it was called and thus I was not able to prove that it was failing. Note also that both function could be re-factorize to follow to default implementation : 
https://github.com/django/django/blob/stable/3.0.x/django/contrib/auth/models.py#L131-L158

I can do it if you want so

**Comment by joncison** [comment]
I just made the change above - although I don't think it was strictly required.

Am I right that the refactoring is to make use of ``**extra_fields`` ?  If so, please go ahead.  Thanks!

**Comment by bryan-brancotte** [comment]
I don't know if it was required either, at least it is done, to be sure.

The refactoring is to make use of ``**extra_fields``, but also create and use the ``_create_user`` but after some thinking I don't think it is necessary as you almost to the same by calling ``create_user`` from ``create_superuser``.

**Comment by joncison** [comment]
I was thinking the same.  Use of ``**extra_fields`` would tidy the code nicely though.

**Pull request merged**
