### PR TITLE
On using black or not to force coherent code formating

### PR DESCRIPTION
**Pull request by bryan-brancotte**
Hi @joncison 

Do you have an opinion on the matter ? In my case I like it, but understand that some people do not like it as the format is fixed with almost no compromise.

I will update this PR to give a view of what it would be

### CODE REVIEW

**Comment by joncison** [comment]
@bryan-brancotte In most cases I prefer the Black code formatting.  In any case, it's very good to have coding standards - so let's go for it!  Inflexibility is good here (I'll get used to the bits I don't like - and it's an overall win to be consistent).

One question - how does this work with my editing environment though?  I use ATOM editor.

**Comment by bryan-brancotte** [comment]
Good :) Great !!

## Config
Concerning the line length, the default is 80 but way too small IMHO, I prefere when possible 120.

## ATOM
Regarding the editor there seems to be modules ([here](https://atom.io/packages/python-black) and [there](https://atom.io/packages/atom-black)). I hope if the configuration is not provided that black will use the pyproject.toml config file.

## PyCharm
(More a not to myself) I'm using Pycharm, and the [integration of Black](https://black.readthedocs.io/en/stable/editor_integration.html) when smoothly.

## pre-commit
Also I configured pre-commit, thus if you configure it (`pre-commit install`), it can can either have black preventing commit to be not normalized, or event let black automatically reformat the code before committing. 

## Github Action
I also added a github action that make the PR fail when black detect that reformatting is needed.

## Questions
 * auto reformat before commit or not ? i.e: have `'--check',` or not in `.pre-commit-config.yaml`
 * Are you ok with line length 120
 * When do you want to pause the development so I can merge the source that will be reformatted ?

**Comment by joncison** [comment]
Hi @bryan-brancotte 

If it's convenient for you, we can pause development now.  You can do the merge and in the meantime I'll try to configure ATOM on Windows (I also have PyCharm, so that's an option too), and set up pre-commit.

Line length 120 is OK (agree 80 is no good)
I think to begin it should not auto-reformat, rather it should prevent the commit.  This way I'll learn the coding style.  Eventually we can put auto-reformat on ?

Thanks !

**Comment by bryan-brancotte** [comment]
Ok for now, 120 and no auto-reformat for now

**Comment by bryan-brancotte** [comment]
closing in favor of #22

**Comment by joncison** [comment]
OK, I think I'm good to go, took a while setting up environment on Windows etc.  Are you happy @bryan-brancotte for me to start editing code again?

**Comment by bryan-brancotte** [comment]
Hi @joncison no problem, I merged #22 so master is clean and ready to accept new code

**Pull request closed without merging**
