### PR TITLE
Custom model admin

### PR DESCRIPTION
**Pull request by bryan-brancotte**
Hi Jon

Here are some suggestion and demo for the admin view. The main part being the EventAdmin and its filter_horizontal which helps *a lot* when adding or removing element from ManyToMany relationship. Some part like short_name_or_name are a little bit "overkill" but they give you an example on how it works.

Cheers

### CODE REVIEW

**Comment by joncison** [comment]
This is excellent !  Thank-you.  Will write back here once I test it out, if I have any questions.

**Comment by joncison** [comment]
Just tested, looks really nice and everything is working, except for filtering "By cost", "By onlineOnly" and "By accessibility".  Filtering "By cost" works OK.  Any ideas?

**Comment by bryan-brancotte** [comment]
The four of them works normally on my local instance, can you send me screenshot/log of the issue ?

**Comment by joncison** [comment]
This is what I get at the command-line when I click on "Yes" in "By onlineOnly" filter:
``[16/Jul/2020 12:11:49] "GET /admin/ifbcatsandbox_api/event/?onlineOnly__exact=1 HTTP/1.1" 200 7333
[16/Jul/2020 12:11:49] "GET /admin/jsi18n/ HTTP/1.1" 200 3223``

Then clicking on "All" in "By onlineOnly" filter:
``[16/Jul/2020 12:13:01] "GET /admin/ifbcatsandbox_api/event/? HTTP/1.1" 200 7230
[16/Jul/2020 12:13:01] "GET /admin/jsi18n/ HTTP/1.1" 200 3223``

This filters results as expected.

If I then click on e.g. "Workshop" in "By type" filter I get
``[16/Jul/2020 12:15:39] "GET /admin/ifbcatsandbox_api/event/?type__exact=WO HTTP/1.1" 200 6042
[16/Jul/2020 12:15:39] "GET /admin/jsi18n/ HTTP/1.1" 200 3223``

The query looks good to me ... although I note it's not using the human-readable name.

PS.  I haven't set up filtering in the browsable API for Event yet.  Not sure if that matters?

**Comment by bryan-brancotte** [comment]
Strange, the log you give me are normal, I have the same and it works here.

Maybe a silly question, but do you have in the database event that are workshop ? If so can you change the type to something else, save it, and then change it back to workshop ?

**Comment by joncison** [comment]
This is strange ... or perhaps I misunderstand something.

When I edited an event (doing as you suggested) in the _browsable API_ it made no difference.

But then I tried editing the event using _Django admin interface_ - the ``Type`` field etc. had blank values, suggesting that the browsable API hadn't actually made the change in the database.  When I manually set the ``Type`` to "Workshop" in Django admin interface, filtering works OK.

So I then gave values to event type, cost and accessibility to my two events using Django admin interface, tested filtering, which works great. 

Now when I GET the events from browsable API, I see the shorthand names e.g. "TR", "PR" etc. for the field values.  And if I look at the "HTML form" to POST data, I see the fields have blank values, but will let me select "Training course", "Private" etc.

So it seems there's a mx-up?

Just noticed your post .. will read it now.

**Comment by bryan-brancotte** [comment]
Yes the issue is a mix up between key and values for choices. The issue is not with the admin view, but the serializer, still searching for a solution

**Pull request merged**
